### ISSUE TITLE
运行samples/multitask/task_master.py时报错

### ISSUE THREAD

**Issue by xjianster** [michaelliao/learn-python3#3]
Traceback (most recent call last):
  File "task_master.py", line 22, in <module>
    manager.start()
  File "...\multiprocessing\managers.py", line 479, in start
    self._process.start()
  File "...\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "...\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "...\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "...\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x00594CD8>: attribute lookup <lambda> on __main__ failed

这是怎么回事

**Comment by d87335903** [comment]
@xjianster ，这个bug有解决方案了吗?

**Comment by littleant1111** [comment]
我已经发邮件给他了，但愿他能抽空看下。
