### ISSUE TITLE
Win10用pycharm执行代码，出现UnicodeDecodeError

### ISSUE THREAD

**Issue by hipurple** [michaelliao/learn-python3#39]
系统:win10，编辑器：pycharm，版本：Python3.7

> C:\ProgramData\Anaconda3\python.exe C:/仙女莉/Python学习/start.py
Traceback (most recent call last):
  File "C:/仙女莉/Python学习/start.py", line 17, in <module>
    server = smtplib.SMTP(smtp_server, 25)  # SMTP协议默认端口是25
  File "C:\ProgramData\Anaconda3\lib\smtplib.py", line 261, in __init__
    fqdn = socket.getfqdn()
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

下面是源码：

> from email.mime.text import MIMEText
msg = MIMEText('hello, send by Python...', 'plain', 'utf-8')
from_addr = input('From: ')
password = input('Password: ')
to_addr = input('To: ')
smtp_server = input('SMTP server: ')
import smtplib
server = smtplib.SMTP(smtp_server, 25) 
server.set_debuglevel(1)
server.login(from_addr, password)
server.sendmail(from_addr, [to_addr], msg.as_string())
server.quit()

**Comment by hipurple** [comment]
求大佬帮助解答，感谢

**Comment by hipurple** [comment]
用了git上的源码，成功了，我去检查下看问题在哪。感谢。
